name: kama_streaming
description: IPTV base app
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.7.0
  http: ^0.13.6
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
